# Generated by Django 5.2.1 on 2025-09-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('good', 'Bom'), ('neutral', 'Neutro'), ('bad', 'Ruim')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
